---
openapi: 3.1.1
info:
    title: Settlement Instructions API
    version: "0.1"
    description: |
        ## Settlement instructions
        ### Description
paths:
    "/v1/custodian":
        get:
            summary: Retrieve the Custodian
            parameters: []
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                "$ref": "#/components/schemas/Custodian"
                "400":
                    description: Bad request
                "401":
                    description: Unauthorized
                "500":
                    description: Internal server error
    "/v1/clients":
        get:
            summary: Retrieve the list of clients that user have access to
            parameters:
                - name: id
                  in: query
                  description: Unique identifier of Client
                  required: false
                  schema:
                      type: array
                      items:
                          type: string
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                items:
                                    "$ref": "#/components/schemas/Client"
                "400":
                    description: Bad request
                "401":
                    description: Unauthorized
                "500":
                    description: Internal server error
    "/v1/settlementinstructions":
        get:
            parameters:
                - name: startTradeDate
                  in: query
                  description: startTradeDate on format YYYY-MM-DD
                  required: false
                  schema:
                      type: string
                      format: date
                - name: tradeDate
                  in: query
                  description: tradeDate on format YYYY-MM-DD
                  required: false
                  schema:
                      type: string
                      format: date
                - name: settlementDate
                  in: query
                  description: settlementDate on format YYYY-MM-DD
                  required: false
                  schema:
                      type: string
                      format: date
                - name: id
                  in: query
                  description: Unique identifier of settlement instruction
                  required: false
                  schema:
                      type: string
                - name: sender
                  in: query
                  description: SettlementInstruction.sender
                  required: false
                  schema:
                      type: string
                - name: status
                  in: query
                  required: false
                  schema:
                      $ref: "#/components/schemas/Status"
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                items:
                                    "$ref": "#/components/schemas/SettlementInstruction"
                "400":
                    description: Bad request
                "401":
                    description: Unauthorized
                "500":
                    description: Internal server error

        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            "$ref": "#/components/schemas/SettlementInstruction"
                required: true
            responses:
                "201":
                    description: Created successfully
                    content:
                        application/json:
                            schema:
                                "$ref": "#/components/schemas/SettlementInstruction"
                "400":
                    description: Bad request
                "401":
                    description: Unauthorized
                "500":
                    description: Internal server error
components:
    schemas:
        Status:
            type: string
            enum:
                - PENDING
                - PROCESSING
                - SETTLED
                - REJECTED
                - DELETED
                - FAILED
        BIC:
            type: string
            description: >
                The Bank Identifier Code (BIC) of an institution.
                Must be an 8 or 11-character alphanumeric code following ISO 9362 format.
            example: "ESSESEGCXXX"
            pattern: "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$"
        ProcedureCode:
            type: string
            description: >
                The settlement procedure code according to ISO 15022 or ISO 20022.
                Indicates the processing procedure for the settlement instruction.

                  - CLOP # Close of Position
                  - OPEP # Open Position
                  - TRAD # Standard Trade Settlement
                  - NETT # Netting Settlement
                  - COLL # Collateral Movement
                  - STLD # Standard Delivery
                  - RPTO # Repo Transaction
            enum:
                - CLOP
                - OPEP
                - TRAD
                - NETT
                - COLL
                - STLD
                - RPTO
            example: "CLOP"
        CFI:
            type: string
            description: |
                The Classification of Financial Instruments (CFI) code according to ISO 10962.
                It is a six-character alphanumeric code that classifies the financial instrument.
                The CFI code is made up of six characters, where:

                 - 1st character: Category of the financial instrument (e.g., E for equities, D for debt).
                 - 2nd character: Group within that category (e.g., common share, preferred share for equities).
                 - 3rd to 6th characters: Attributes that describe further characteristics (e.g., voting rights, payment status).

                | Position | Attribute                         | Example                              |
                |----------|-----------------------------------|--------------------------------------|
                | 1        | Category of instrument            | E (Equity), D (Debt), O (Options), R (Rights) |
                | 2        | Group within the category         | S (Common Share), B (Bond), O (Option) |
                | 3        | Attribute (Voting rights)         | V (Voting), N (Non-voting)           |
                | 4        | Attribute (Payment status)        | U (Fully paid), P (Partially paid)   |
                | 5        | Attribute (Form)                  | F (Registered), B (Bearer)           |
                | 6        | Attribute (Ranking)               | L (Subordinate), H (High ranking)    |

            example: ESVUFB
            pattern: "^[A-Z0-9]{6}$"
        CurrencyEnum:
            type: string
            enum:
                - AUD
                - BRL
                - CAD
                - CHF
                - CNY
                - DKK
                - EUR
                - GBP
                - HKD
                - INR
                - JPY
                - KRW
                - MXN
                - NOK
                - NZD
                - RUB
                - SEK
                - SGD
                - TRY
                - USD
                - ZAR
        Custodian:
            type: object
            required:
                - id
                - longName
                - legalEntityIdentifier
                - settlementInstructionReceiverId
            properties:
                id:
                    description: Unique identifier of Client. Set by the custodian
                    type: string
                longName:
                    type: string
                legalEntityIdentifier:
                    description: "[LEI code](https://en.wikipedia.org/wiki/Legal_Entity_Identifier)"
                    type: string
                settlementInstructionReceiverId:
                    type: string
        Client:
            type: object
            required:
                - id
                - longName
                - legalEntityIdentifier
                - settlementInstructionSenderId
                - accountNumber
                - standardSettlementInstructions
            properties:
                id:
                    description: Unique identifier of Client. Set by the custodian
                    type: string
                longName:
                    type: string
                legalEntityIdentifier:
                    description: "[LEI code](https://en.wikipedia.org/wiki/Legal_Entity_Identifier)"
                    type: string
                accountNumber:
                    type: string
                settlementInstructionSenderId:
                    type: string
                standardSettlementInstructions:
                    description: Settlement instructions for this client
                    schema:
                        items:
                            "$ref": "#/components/schemas/StandardSettlementInstruction"
        SettlementInstruction:
            type: object
            required:
                - sender
                - receiver
                - referenceNumber
                - type
                - settlementDate
                - tradeDate
                - dealAmount
                - currency
                - securityDescription
                - class
                - denominationCurrency
                - expiryDate
                - size
                - procedure
                - safeAccount
                - executionAmount
                - settlementAmount
            properties:
                id:
                    description: Unique identifier of SettlementInstruction. Set by the custodian
                    type: string
                externalId:
                    type: string
                    description: Unique identifier of SettlementInstruction. Set by the client. Set as idempotency id.
                sender:
                    description: Use Client.settlementInstructionSenderId
                receiver:
                    description: Use Custodian.settlementInstructionReceiverId
                type:
                    type: string
                    description: Message type identifier
                    example: "O5981148"
                settlementDate:
                    type: string
                    format: date
                    description: Settlement date in ISO format
                    example: "2018-01-01"
                tradeDate:
                    type: string
                    format: date
                    description: Trade date in ISO format
                    example: "2018-01-03"
                dealAmount:
                    type: number
                    format: double
                    description: Total deal amount
                    example: 15200000
                currency:
                    $ref: "#/components/schemas/CurrencyEnum"
                securityDescription:
                    type: string
                    description: Description of the security involved in the trade
                    example: "Sec desc"
                isin:
                    type: string
                    description: "[ISIN (International Securities Identification Number)](https://en.wikipedia.org/wiki/International_Securities_Identification_Number)"
                class:
                    $ref: "#/components/schemas/CFI"
                denominationCurrency:
                    $ref: "#/components/schemas/CurrencyEnum"
                expiryDate:
                    type: string
                    format: date
                    description: Expiry date of the security
                    example: "2018-01-03"
                size:
                    type: number
                    format: double
                    description: Size or quantity of the security being traded
                    example: 1000000
                procedure:
                    $ref: "#/components/schemas/ProcedureCode"
                sellerId:
                    $ref: "#/components/schemas/BIC"
                sellerName:
                    type: string
                    description: Name of the seller party (optional)
                    example: "Seller Bank"
                buyerId:
                    $ref: "#/components/schemas/BIC"
                buyerName:
                    type: string
                    description: Name of the buyer party (optional)
                    example: "Buyer Bank"
                deliveringAgentId:
                    $ref: "#/components/schemas/BIC"
                deliveringAgentName:
                    type: string
                    description: Name of the delivering agent party (optional)
                    example: "Delivering Agent"
                receivingAgentId:
                    description: Id of the receiving agent party (optional)
                    $ref: "#/components/schemas/BIC"
                receivingAgentName:
                    type: string
                    description: Name of the receiving agent party (optional)
                    example: "Receiving Agent"
                safeAccount:
                    type: string
                    description: Safe account identifier
                    example: "9999999"
                executionAmount:
                    type: number
                    format: double
                    description: The amount involved in the execution of the trade
                    example: 15200000
                settlementAmount:
                    type: number
                    format: double
                    description: The amount involved in the settlement of the trade
                    example: 15200000
                status:
                    $ref: "#/components/schemas/Status"
                history:
                    type: array
                    items:
                        type: object
                        properties:
                            status:
                                $ref: "#/components/schemas/Status"
                            message:
                                type: string
                            updateTimestamp:
                                type: string
                            format: date-time
                updateTimestamp:
                    type: string
                    format: date-time
                    description: Read-only
                createTimestamp:
                    type: string
                    format: date-time
                    description: Read-only
        StandardSettlementInstruction:
            type: object
            required:
                - id
                - agentBusinessIdentifierCode
                - beneficiaryBusinessIdentifierCode
                - iban
                - placeOfSettlement
                - securityAccount
                - buyerSellerSafe
                - type
                - tradeType
            properties:
                id:
                    type: string
                    description: Unique identifier of the standard settlement instruction. Set by the custodian
                market:
                    type: string
                    description: Market can be for example SWEDEN, BELGIUM or EUROCLEAR etc
                    example: EUROCLEAR
                agentBusinessIdentifierCode:
                    description: Business Identifier Code of the agent
                    $ref: "#/components/schemas/BIC"
                beneficiaryBusinessIdentifierCode:
                    description: Business Identifier Code of the beneficiary
                    $ref: "#/components/schemas/BIC"
                iban:
                    type: string
                    description: "[IBAN (International Bank Account Number)](https://en.wikipedia.org/wiki/International_Bank_Account_Number)"
                    pattern: "^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$"
                    example: "GB33BUKB20201555555555"
                currency:
                    $ref: "#/components/schemas/CurrencyEnum"
                placeOfSettlement:
                    type: string
                    description: Place of settlement
                    $ref: "#/components/schemas/BIC"
                    example: VPCSSESSXXX
                securityAccount:
                    type: string
                    description: Security account number
                buyerSellerSafe:
                    type: string
                    description: Safe code for the buyer or seller
                type:
                    type: string
                    description: Type of settlement instruction
                    enum:
                        - Equity
                        - FixedIncome
                tradeType:
                    type: string
                    description: Trade type
                    enum:
                        - Collateral
                        - Security
